app = "jenovabot"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PREFIX = "!"
DATA_FILE = "data/data.json"

[mounts]
source = "jenovabot_files"
destination = "/docker/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
