# fly.toml file generated for jenovabot on 2022-12-16T18:13:21-05:00

app = "jenovabot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
CURRENT_STREAM_NAME = "Umineko When They Cry"
PREFIX = "!"
DATA_FILE = "data/data.json"
LAVALINK_HOST = "nonssl.freelavalink.ga"
LAVALINK_PORT = "80"
LAVALINK_PASS = "www.freelavalink.ga"

[mounts]
source = "jenovabot_files"
destination = "/docker/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
