app = "jenovabot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
CURRENT_STREAM_NAME = "Umineko When They Cry"
PREFIX = "!"
DATA_FILE = "data/data.json"
LAVALINK_HOST = "lava1.horizxon.studio"
LAVALINK_PORT = "80"
LAVALINK_PASS = "horizxon.studio"

[mounts]
source = "jenovabot_files"
destination = "/docker/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true