app = 'jenovabot-lavalink'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = 5

[http_service]
  internal_port = 2333
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[experimental]
  auto_rollback = true